---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/bookmarks

- Developer:
    - Github:
        - abbr: GH
          href: https://github.com/
    - Cloudflare Dashboard:
        - abbr: CF
          href: https://dash.cloudflare.com/
    - FlowVPS Dashboard:
        - abbr: FV
          href: https://control.flowvps.com/
    - FlowVPS Billing:
        - abbr: FV
          href: https://billing.flowvps.com/

- Social:
    - Reddit:
        - abbr: RE
          href: https://reddit.com/

- Entertainment:
    - YouTube:
        - abbr: YT
          href: https://youtube.com/
