---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/docker/

# localdocker:
#   host: dockerproxy
#   port: 443
#   protocol: https

# my-docker:
#   socket: /var/run/docker.sock
