---
services:
  nginx:
    container_name: nginx-demo-1
    image: nginx:latest
    networks:
      - frontend
    labels:
      - traefik.enable=true
      - traefik.http.routers.nginx-https.tls=true
      - traefik.http.routers.nginx-https.tls.certresolver=cloudflare
      - traefik.http.routers.nginx-https.entrypoints=websecure
      - traefik.http.routers.nginx-https.rule=Host(`nginx.srv-1.home.doubie.dev`)
      - traefik.http.routers.nginx-https.middlewares=authelia@docker
    restart: unless-stopped
networks:
  frontend:
    external: true
