---
services:
  bind9:
    image: ubuntu/bind9:9.18-24.04_beta
    container_name: bind9
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - ./config:/etc/bind
      - ./cache:/var/cache/bind
      - ./records:/var/lib/bind
    restart: unless-stopped
    environment:
      - BIND9_USER=root
      - TZ=Australia/Melbourne
