---
services:
  cloudflare-tunnel:
    image: cloudflare/cloudflared:2025.4.0
    container_name: cloudflare-tunnel
    networks:
      - frontend
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    command: tunnel --no-autoupdate run
    restart: unless-stopped
networks:
  frontend:
    external: true
