---
services:
  postgresql:
    image: docker.io/library/postgres:16-alpine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/authentik_postgres_password
      POSTGRES_USER_FILE: /run/secrets/authentik_postgres_user
      POSTGRES_DB_FILE: /run/secrets/authentik_postgres_db
      TZ: Australia/Melbourne
    secrets:
      - authentik_postgres_password
      - authentik_postgres_user
      - authentik_postgres_db
    networks:
      backend:
        aliases:
          - postgresql
    deploy:
      placement:
        constraints:
          - node.hostname == srv-1
      restart_policy:
        condition: on-failure

  redis:
    image: docker.io/library/redis:alpine
    command: --save 60 1 --loglevel warning
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    volumes:
      - redis:/data
    environment:
      TZ: Australia/Melbourne
    networks:
      backend:
        aliases:
          - redis
    deploy:
      placement:
        constraints:
          - node.hostname == srv-1
      restart_policy:
        condition: on-failure


  server:
    image: ghcr.io/goauthentik/server:2026.5
    command: server
    environment:
      AUTHENTIK_SECRET_KEY: file:///run/secrets/authentik_secret_key
      AUTHENTIK_REDIS__HOST: redis
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__USER: file:///run/secrets/authentik_postgres_user
      AUTHENTIK_POSTGRESQL__NAME: file:///run/secrets/authentik_postgres_db
      AUTHENTIK_POSTGRESQL__PASSWORD: file:///run/secrets/authentik_postgres_password
      AUTHENTIK_ERROR_REPORTING__ENABLED: "true"
      AUTHENTIK_LISTEN__HTTP: 0.0.0.0:9001
      TZ: Australia/Melbourne
    secrets:
      - authentik_secret_key
      - authentik_postgres_user
      - authentik_postgres_db
      - authentik_postgres_password
    volumes:
      - ./media:/media
      - ./custom-templates:/templates
    networks:
      - backend
      - frontend
    deploy:
      placement:
        constraints:
          - node.hostname == srv-1
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.swarm.network=frontend
        - traefik.http.routers.authentik.rule=Host(`authentik.doubie.dev`)
        - traefik.http.routers.authentik.entrypoints=websecure
        - traefik.http.routers.authentik.tls=true
        - traefik.http.routers.authentik.tls.certresolver=cloudflare
        - traefik.http.routers.authentik.service=authentik-svc
        - traefik.http.services.authentik-svc.loadbalancer.server.port=9001

  worker:
    image: ghcr.io/goauthentik/server:2026.5
    command: worker
    user: root
    environment:
      AUTHENTIK_SECRET_KEY: file:///run/secrets/authentik_secret_key
      AUTHENTIK_REDIS__HOST: redis
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__USER: file:///run/secrets/authentik_postgres_user
      AUTHENTIK_POSTGRESQL__NAME: file:///run/secrets/authentik_postgres_db
      AUTHENTIK_POSTGRESQL__PASSWORD: file:///run/secrets/authentik_postgres_password
      AUTHENTIK_ERROR_REPORTING__ENABLED: "true"
      TZ: Australia/Melbourne
    secrets:
      - authentik_secret_key
      - authentik_postgres_user
      - authentik_postgres_db
      - authentik_postgres_password
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./media:/media
      - ./certs:/certs
      - ./custom-templates:/templates
    networks:
      - backend
    deploy:
      placement:
        constraints:
          - node.hostname == srv-1
      restart_policy:
        condition: on-failure

  ldap_outpost:
    image: ghcr.io/goauthentik/ldap:2026.5.6
    # Optionally specify the container's network, which must be able to reach the core authentik server.
    networks:
      - frontend
      - backend
    ports:
      # - 389:3389
      - 636:6636
    environment:
      AUTHENTIK_HOST: https://authentik.doubie.dev
      AUTHENTIK_INSECURE: "false"
      AUTHENTIK_TOKEN: file:///run/secrets/authentik_ldap_token
    secrets:
      - authentik_ldap_token
    deploy:
      placement:
        constraints:
          - node.hostname == srv-1
      restart_policy:
        condition: on-failure

volumes:
  database:
    name: authentik_database
    external: true
  redis:
    name: authentik_redis
    external: true

networks:
  frontend:
    external: true
  backend:
    external: true
secrets:
  authentik_secret_key:
    external: true
  authentik_postgres_user:
    external: true
  authentik_postgres_db:
    external: true
  authentik_postgres_password:
    external: true
  authentik_ldap_token:
    external: true
