---
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v1.3.2
    container_name: homepage
    networks:
      - frontend
    ports:
      - 3000:3000
    volumes:
      - ./config:/app/config
      - ./images:/app/public/images
      - ./icons:/app/public/icons
      # - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations, see alternative methods
    environment:
      HOMEPAGE_ALLOWED_HOSTS: homepage.srv-1.home.doubie.dev,192.168.2.1:3000 # required, may need port. See gethomepage.dev/installation/#homepage_allowed_hosts
      PUID: 1000
      PGID: 1000
    labels:
      - traefik.enable=true
      - traefik.http.routers.homepage.tls=true
      - traefik.http.routers.homepage.tls.certresolver=cloudflare
      - traefik.http.routers.homepage.entrypoints=websecure
      - traefik.http.routers.homepage.rule=Host(`homepage.srv-1.home.doubie.dev`)
      - traefik.http.services.homepage.loadbalancer.server.port=3000
      - traefik.http.routers.homepage.service=homepage
    restart: unless-stopped
networks:
  frontend:
    external: true
