---
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    networks:
      - frontend
    ports:
      - 8096:8096
    volumes:
      - ./config:/config
      - ./cache:/cache
      - type: bind
        source: /mnt/data/media
        target: /media
    restart: 'unless-stopped'
    # Optional - alternative address used for autodiscovery
    environment:
      - JELLYFIN_PublishedServerUrl=https://jellyfin.srv-1.home.doubie.dev
      - TZ=Australia/Melbourne
    labels:
      - traefik.enable=true
      - traefik.http.routers.jellyfin.tls=true
      - traefik.http.routers.jellyfin.tls.certresolver=cloudflare
      - traefik.http.routers.jellyfin.entrypoints=websecure,web
      - traefik.http.routers.jellyfin.rule=Host(`jellyfin.srv-1.home.doubie.dev`)
      - traefik.http.routers.jellyfin.service=jellyfin
      - traefik.http.services.jellyfin.loadbalancer.server.port=8096
      - traefik.http.routers.jellyfin.middlewares=authentik@file
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    extra_hosts:
      - 'host.docker.internal:host-gateway'
networks:
  frontend:
    external: true
