# For configuration options and examples, please see:
---
# https://gethomepage.dev/configs/services/

- Infrastructure & Networking:
    - Proxmox:
        href: https://pve-1.doubie.dev:8006
        description: Proxmox VE 1
        icon: proxmox.png
        siteMonitor: https://pve-1.doubie.dev:8006
        widget:
          type: proxmox
          url: https://pve-1.doubie.dev:8006
          username: {{HOMEPAGE_FILE_PROXMOX_USERNAME}}
          password: {{HOMEPAGE_FILE_PROXMOX_PASSWORD}}
    - Proxmox:
        href: https://pve-2.doubie.dev:8006
        description: Proxmox VE 2
        icon: proxmox.png
        siteMonitor: https://pve-2.doubie.dev:8006
        widget:
          type: proxmox
          url: https://pve-2.doubie.dev:8006
          username: {{HOMEPAGE_FILE_PROXMOX_USERNAME}}
          password: {{HOMEPAGE_FILE_PROXMOX_PASSWORD}}
    - Traefik:
        href: https://traefik.doubie.dev
        # description: traefik on srv-1
        icon: traefik.png
        siteMonitor: https://traefik.doubie.dev
    - Router:
        href: http://192.168.0.1/
        description: Router admin portal
        icon: router.png

- Management, Security and Identity:
    - Portainer:
        href: https://portainer.doubie.dev
        # description: portainer on srv-1
        icon: portainer.png
        siteMonitor: https://portainer.doubie.dev
    - Authentik:
        href: https://authentik.doubie.dev
        # description: authentik on srv-1
        icon: authentik.png
        siteMonitor: https://authentik.doubie.dev
    - Netbird:
        href: https://netbird.doubie.dev
        # description: netbird on srv-1
        icon: netbird.png
        siteMonitor: https://netbird.doubie.dev
    - Syncthing:
        href: https://syncthing.doubie.dev
        # description: syncthing on srv-1
        icon: syncthing.png
        siteMonitor: https://syncthing.doubie.dev

- Services:
    - Nextcloud:
        href: https://nc.doubie.dev
        # description: nextcloud on srv-1
        icon: nextcloud.png
        siteMonitor: https://nc.doubie.dev
    - Jellyfin:
        href: https://jellyfin.doubie.dev
        # description: jellyfin media server
        icon: jellyfin.png
        siteMonitor: https://jellyfin.doubie.dev
    - Radarr:
        href: https://radarr.doubie.dev
        # description: radarr on srv-1
        icon: radarr.png
        siteMonitor: https://radarr.doubie.dev
    - Nginx:
        href: https://nginx.doubie.dev
        # description: nginx web server
        icon: nginx.png
        siteMonitor: https://nginx.doubie.dev
