# For configuration options and examples, please see:
---
# https://gethomepage.dev/configs/services/

- Infrastructure & Networking:
    - Proxmox:
        href: https://pve-1.home.doubie.dev:8006
        description: Proxmox VE 1
        icon: proxmox.png
        siteMonitor: https://pve-1.home.doubie.dev:8006
        widget:
          type: proxmox
          url: https://pve-1.home.doubie.dev:8006
          username: {{HOMEPAGE_VAR_PROXMOX_USERNAME}}
          password: {{HOMEPAGE_VAR_PROXMOX_PASSWORD}}
    - Traefik:
        href: https://traefik.srv-1.home.doubie.dev
        description: traefik on srv-1
        icon: traefik.png
        siteMonitor: https://traefik.srv-1.home.doubie.dev
    - Router:
        href: http://192.168.0.1/
        description: Router admin portal
        icon: router.png

- Management:
    - Portainer:
        href: https://portainer.srv-1.home.doubie.dev
        description: portainer on srv-1
        icon: portainer.png
        siteMonitor: https://portainer.srv-1.home.doubie.dev

- Security and Identity:
    - Authentik:
        href: https://authentik.srv-1.home.doubie.dev
        description: authentik on srv-1
        icon: authentik.png
        siteMonitor: https://authentik.srv-1.home.doubie.dev
    - Netbird:
        href: https://netbird.srv-1.home.doubie.dev
        description: netbird on srv-1
        icon: netbird.png
        siteMonitor: https://netbird.srv-1.home.doubie.dev

- Services:
    - Nginx:
        href: https://nginx.srv-1.home.doubie.dev
        description: nginx web server
        icon: nginx.png
        siteMonitor: https://nginx.srv-1.home.doubie.dev
    - Jellyfin:
        href: https://jellyfin.srv-1.home.doubie.dev
        description: jellyfin media server
        icon: jellyfin.png
        siteMonitor: https://jellyfin.srv-1.home.doubie.dev
    - Radarr:
        href: https://radarr.srv-1.home.doubie.dev
        description: radarr on srv-1
        icon: radarr.png
        siteMonitor: https://radarr.srv-1.home.doubie.dev
